config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#index'

  # external informations
  get '/home', to: 'application#home', as: 'home'

  # tables resources
  resources :tables do
    resources :order_sessions
  end
  post 'tables/:id/edit', to: 'tables#update', as: 'place_order'
  get 'tables/:id/qr', to: 'tables#generate_qr', as: 'generate_qr'

  # sessions resources
  resources :sessions, only: %i[new create destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # users resources
  resources :users, only: %i[new create edit update show destroy]
  get 'signup', to: 'users#new', as: 'signup'

  # orders resources
  delete 'order/:id', to: 'orders#pay', as: 'order'
  delete 'orders', to: 'orders#pay_group', as: 'orders'

  # organizations resources
  resources :organizations, only: %i[show edit update destroy]

  # roles resources
  resources :roles, only: %i[new create show edit update destroy]

  resources :dishes
  resources :drinks

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
# frozen_string_literal: true

# User model
class User < ApplicationRecord
  has_secure_password
  has_many :questions, dependent: :destroy
  has_many :votes, dependent: :destroy
  belongs_to :organization
  belongs_to :role

  validates :email, presence: true, format: {
    with: /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  }, uniqueness: true
  validates :username, presence: true, uniqueness: true, length: {
    minimum: 5,
    maximum: 70
  }
  validates :firstname, presence: true, length: {
    minimum: 3,
    maximum: 50
  }
  validates :lastname, presence: true, length: {
    minimum: 2,
    maximum: 70
  }
  validates :gender, presence: true, format: {
    with: /(male|female)/
  }
  validates :password_digest, presence: true
  validates :email, presence: true, uniqueness: true, length: {
    minimum: 8,
    maximum: 70
  }, format: {
    with: /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  }
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  ##
  # Set the user with id provided by request route
  before_action :set_user, only: %i[show edit update destroy]

  ##
  # check if current user is authenticated or else redirect
  before_action :authorize, only: %i[show edit update destroy index create]

  ##
  # check if current user has admin role or else redirect
  before_action :check_authorization, only: %i[index new create destroy]

  ##
  # GET /users
  # Index displays a list of all users that belong to the
  # organization of the current user.
  #
  # Access: Admin
  def index
    @users = User.where(organization_id: organization.id)
  end

  ##
  # GET /users/1
  # GET /users/1.json
  # Returns the user specified by :id path parameter
  def show; end

  ##
  # GET /users/new
  # Returns a view for creating a new User.
  #
  # Access: Admin
  def new
    @user = User.new
  end

  ##
  # GET /users/:id/edit
  # Return a edit view for the user provided by the
  # :id path parameter.
  #
  # path: :id
  # Access: Registered User
  def edit; end

  ##
  # POST /users
  # POST /users.json
  # Create new User Entry for current organization.
  #
  # Access: Admin
  def create
    @user = User.new(user_params)
    organization.roles.find(params[:user][:role]).users << @user
    organization.users << @user
    respond_to do |format|
      if @user.save
        authenticate(@user)
        format.html do
          redirect_to @user,
                      notice: 'User was successfully created.'
        end
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  ##
  # PATCH/PUT /users/:id
  # PATCH/PUT /users/:id.json
  # update user specified by :id
  #
  # Access: Registered User
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html do
          redirect_to @user,
                      notice: 'User was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  ##
  # DELETE /users/:id
  # DELETE /users/:id.json
  # Delete user specified by :id
  #
  # Access: Admin
  def destroy
    log_out_user
    @user.destroy
    respond_to do |format|
      format.html do
        redirect_to users_url,
                    notice: 'User was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

  ##
  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(session[:user_id])
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def user_params
    params.require(:user).permit(
      :username,
      :firstname,
      :lastname,
      :gender,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

# Helper module for users
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :username %>
    <%= form.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :firstname %>
    <%= form.text_field :firstname, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :lastname %>
    <%= form.label :lastname, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :gender %>
    <%= form.select :gender, [['male', 'male'], ['female', 'female']], class: "form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, class: "form-control" %>
  </div>

  <%if admin? %>
  <div class="form-group">
    <%= form.label :role %>
    <%= form.select :role, organization.roles.collect { |role| [role.name, role.id]}, class: "form-control"%>
  </div>
  <% end %>
  <div class="actions">
    <%= form.submit class: "form-control btn btn-success" %>
  </div>
<% end %>

app/views/users/_list.html.erb
<ul class="list-group card-text">
    <% users.each do |u| %>
        <li class="list-group-item"><%= link_to u.username, u %></li>
    <% end %>
</ul>

app/views/users/edit.html.erb
<h1>Edit <%= @user.username %></h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %>
<%= link_to 'Back', :back %>

app/views/users/index.html.erb
<h1>All User of <%= current_user.organization.name %></h1>

<%= render 'list', users: @users %>
<% if admin? %><%= link_to 'New User', new_user_url, class: "btn btn-primary card-link" %><% end %>
<%= link_to 'Back', :back %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', :back %>

app/views/users/show.html.erb
<h1><%= @user.username %></h1>
<ul class="list-group">
    <li class="list-group-item"><strong>Name: </strong><%= @user.username %></li>
    <li class="list-group-item"><strong>Email: </strong><%= @user.email %></li>
</ul>
<%= link_to 'Edit', edit_user_path(@user) %>
<%= link_to 'Back', :back %>