config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#index'

  # external informations
  get '/home', to: 'application#home', as: 'home'

  # tables resources
  resources :tables do
    resources :order_sessions
  end
  post 'tables/:id/edit', to: 'tables#update', as: 'place_order'
  get 'tables/:id/qr', to: 'tables#generate_qr', as: 'generate_qr'

  # sessions resources
  resources :sessions, only: %i[new create destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # users resources
  resources :users, only: %i[new create edit update show destroy]
  get 'signup', to: 'users#new', as: 'signup'

  # orders resources
  delete 'order/:id', to: 'orders#pay', as: 'order'
  delete 'orders', to: 'orders#pay_group', as: 'orders'

  # organizations resources
  resources :organizations, only: %i[show edit update destroy]

  # roles resources
  resources :roles, only: %i[new create show edit update destroy]

  resources :dishes
  resources :drinks

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order_session.rb
# frozen_string_literal: true

# Order Group model
class OrderSession < ApplicationRecord
  has_many :orders
  belongs_to :organization
  belongs_to :table

  validates :open, presence: true
end

app/controllers/order_sessions_controller.rb
# frozen_string_literal: true

class OrderSessionsController < ApplicationController
  before_action :authorize
  before_action :check_authorization, only: %i[index]
  before_action :set_order_session, only: %i[show update edit destroy]

  def index
    if table.order_sessions.where(open: true).size == 1
      session = table.order_sessions.where(open: true).first
      redirect_to edit_table_order_session_path(session.table_id, session)
    else
      redirect_to new_table_order_session_path
    end
  end

  def new
    @order_session = OrderSession.new
    @food = organization.dishes
    @drinks = organization.drinks
  end

  def create
    puts params.to_json
    session = OrderSession.new(table: table, organization: organization, open: true)
    create_orders
    if session.save
      redirect_to edit_table_order_session_path(session.table.id, session.id)
    else
      redirect_to :new
    end
  end

  def edit
    @order_session = set_order_session
    @food = organization.dishes
    @drinks = organization.drinks
  end

  def update
    create_orders
    redirect_to table
  end

  def destroy
    @session = set_order_session
    @session.open = false
    @session.save
  end

  private

  def permit_orders
    params.require(:order_session).permit!
  end

  def set_order_session
    OrderSession.find(params[:id])
  end

  def table
    Table.where(id: params[:table_id]).first
  end

  def create_orders
    params[:order_session].each do |product, quantity|
      quantity.to_i.times do
        order = Order.new(dish: Dish.where(name: product).first, organization: organization, order_session: set_order_session)
        unless order.save
          puts order.errors.to_json
        end
      end
    end
  end
end

app/helpers/order_sessions_helper.rb
# frozen_string_literal: true

module OrderSessionsHelper
end

app/views/order_sessions/_order_form.html.erb
<%= form_with(url: url, model: order_session, local: true) do |form| %>
<ul class="list-group">
    <% @food.order(:category_id).each do |p| %>
    <li class="list-group-item">
    <div class="form-group">
        <p><%= p.name %> - <%= p.category.name %></p>
        <%= form.number_field p.name, value: 0, class: "form-control"%>
    </div>
    </li>
    <% end %>
</ul>
<ul class="list-group">
    <% @drinks.order(:category_id).each do |d| %>
    <li class="list-group-item">
        <div class="form-group">
            <p><%= d.name %></p>
            <%= form.number_field d.name, value: 0, class: "form-control"%>
        </div>
    </li>
    <% end %>
</ul>
<%= form.submit class: "btn btn-primary form-control" %>
<% end %>

app/views/order_sessions/_view.html.erb
<h3>OrderSession for table <%= params[:table_id] %></h3>

<h4>Please select your order</h4>
<%= render 'order_form', order_session: @order_session, url: url %>

app/views/order_sessions/edit.html.erb
<%= render 'view', url: table_order_session_path %>

app/views/order_sessions/new.html.erb
<h3>OrderSession for table <%= params[:table_id] %></h3>

<h4>Please select your order</h4>
<%= render 'order_form', order_session: @order_session, url: table_order_sessions_url %>