config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'application#index'

  # external informations
  get '/home', to: 'application#home', as: 'home'

  # tables resources
  resources :tables do
    resources :order_sessions
  end
  post 'tables/:id/edit', to: 'tables#update', as: 'place_order'
  get 'tables/:id/qr', to: 'tables#generate_qr', as: 'generate_qr'

  # sessions resources
  resources :sessions, only: %i[new create destroy]
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  # users resources
  resources :users, only: %i[new create edit update show destroy]
  get 'signup', to: 'users#new', as: 'signup'

  # orders resources
  delete 'order/:id', to: 'orders#pay', as: 'order'
  delete 'orders', to: 'orders#pay_group', as: 'orders'

  # organizations resources
  resources :organizations, only: %i[show edit update destroy]

  # roles resources
  resources :roles, only: %i[new create show edit update destroy]

  resources :dishes
  resources :drinks

  resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/tables_controller.rb
# frozen_string_literal: true

class TablesController < ApplicationController
  before_action :set_table, only: %i[show edit update destroy generate_qr]
  before_action :set_order, only: [:show]
  before_action :authorize
  before_action :check_authorization, only: %i[new create destroy]
  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.where(organization_id: organization.id)
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @session = @table.order_sessions.select { |s| s.open?}.first
    puts @session.to_json
    if @session.nil?
      redirect_to new_table_order_session_url(@table)
    end
  end

  # GET /tables/new
  def new
    @table = Table.new
  end

  # GET /tables/1/edit
  def edit
    @food = organization.dishes
    @drinks = organization.drinks
  end

  # POST /tables
  # POST /tables.json
  def create
    respond_to do |format|
      if organization.tables.create(table_params)
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render :show, status: :created, location: @table }
      else
        format.html { render :new }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tables/1
  # PATCH/PUT /tables/1.json
  def update
    @orders = orders
    table = Table.find(@orders[:table])
    @orders.delete(:table)
    @drinks = []
    @food = []
    @orders.each do |o|
      o[1].to_i.times do
        order = Order.new
        Table.find(table).orders << order
        Product.find_by(name: o[0].to_s).orders << order
        product = Product.find_by(name: o[0].to_s)
        if product.food
          @food << product
        else
          @drinks << product
        end
        order.save
      end
    end
    redirect_to table, notice: 'Bestellung aufgenommen'
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table.destroy
    respond_to do |format|
      format.html do
        redirect_to tables_url,
                    notice: 'Table was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def generate_qr
    if @table
      respond_to do |format|
        format.svg do
          render inline: RQRCode::QRCode.new(
            "http://localhost:3000/tables/#{@table.id}/"
          ).as_svg
        end
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_table
    @table = Table.where(
      id: params[:id],
      organization_id: organization.id
    ).first
  end

  def set_order
    @order = Order.new
  end

  # Never trust parameters from the scary internet,
  # only allow the white list through.
  def table_params
    params.require(:table).permit(:id)
  end

  # Or if there is no specified sum of them... permit all! ^^'
  def orders
    params.permit!
  end
end

app/helpers/tables_helper.rb
# frozen_string_literal: true

# helper module for tables
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_with(model: table, local: true) do |form| %>
  <% if table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% table.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :number %>
    <%= form.number_field :number, class: 'form-control', min: 0 %>
  </div>

  <div class="form-group">
    <%= form.submit 'Tisch erstellen', class: 'form-control btn btn-success' %>
  </div>
<% end %>

app/views/tables/_list.html.erb
<ul class="list-group card-text">
    <% tables.each do |t| %>
        <li class="list-group-item"><%= link_to t.number, t %></li>
    <% end %>
</ul>

app/views/tables/_pay_list.html.erb
<h3>Open Positions</h3>
<%= %>
<ul class="list-group">
<% orders.each do |o| %>
    <% if not o.paid? %>
    <li class="list-group-item">
        <div class="row">
            <div class="col col-sm-8">
            <%= (o.dish.nil?) ? (o.drink.name + o.drink.quantity) : o.dish.name %> - <%= (o.dish.nil?) ? o.drink.price : o.dish.price %>
            </div>
            <div class="col col-sm-4">
                <%=%>
            </div>
        </div>
        <hr/>
        <div class="row">
            <div class="col col-sm-12">
            <%= link_to 'pay', '/order/' + o.id.to_s, class:"btn btn-warning", style: 'float: right; width: 100%', method: 'delete'%>
            </div>
        </div>
    </li>
    <% end %>
<% end %>
</ul>

app/views/tables/edit.html.erb
<h1>Editing Table</h1>

<!--<%= render 'form', table: @table %>-->
<%= render 'order_form', order: @order %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<h1>Tables</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tables.each do |table| %>
      <tr>
        <td><%= table.number %></td>
        <td><%= link_to 'Show', table %></td>
        <td><%= link_to 'Edit', edit_table_path(table) %></td>
        <td><%= link_to 'Destroy', table, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<script type="text/javascript" src="assets/instascan.min.js"></script>
<video id="preview"></video>
<script type="text/javascript">
  let scanner = new Instascan.Scanner({ video: document.getElementById('preview') });
  scanner.addListener('scan', function (content) {
    console.log(content);
  });
  Instascan.Camera.getCameras().then(function (cameras) {
    if (cameras.length > 0) {
      scanner.start(cameras[0]);
    } else {
      console.error('No cameras found.');
    }
  }).catch(function (e) {
    console.error(e);
  });
</script>
<%= link_to 'New Table', new_table_path %>

app/views/tables/show.html.erb
<h1>Table Number:<%= @table.number %></h1>
<%= link_to 'Bestellen', table_order_sessions_path(@table), class: "btn btn-primary form-control order" %>
<%= render 'pay_list', orders: @session.orders %>
<button id="pay-group" class="btn btn-primary form-control" hidden="true">Bezahlen</button>